export interface MockCustomer {
  _id: string;
  customerId: string;
  name: string;
  age: number;
  gender: string;
  income: number;
  occupation: string;
  education: string;
  city: string;
  country: string;
  purchaseFrequency: number;
  annualSpending: number;
  lastPurchaseDate: string;
  numberOfOrders: number;
  averageOrderValue: number;
  preferredCategory: string;
  customerRating: number;
  clusterId: number;
  segmentName: string;
  clusterBadge: string;
  clusterColor: string;
  churnRisk: 'Low' | 'Medium' | 'High';
  lifetimeValue: number;
  createdAt: string;
  updatedAt: string;
}

export const initialMockCustomers: MockCustomer[] = [
  {
    _id: 'cust_1',
    customerId: 'CUST-1001',
    name: 'Sophia Martinez',
    age: 34,
    gender: 'Female',
    income: 85000,
    occupation: 'Software Engineer',
    education: 'Master',
    city: 'Hyderabad',
    country: 'India',
    purchaseFrequency: 18,
    annualSpending: 4200,
    lastPurchaseDate: '2026-07-28',
    numberOfOrders: 24,
    averageOrderValue: 175,
    preferredCategory: 'Electronics',
    customerRating: 4.8,
    clusterId: 0,
    segmentName: 'High Value / Premium Customers',
    clusterBadge: 'Premium',
    clusterColor: '#3B82F6',
    churnRisk: 'Low',
    lifetimeValue: 10450,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_2',
    customerId: 'CUST-1002',
    name: 'Liam Johnson',
    age: 42,
    gender: 'Male',
    income: 95000,
    occupation: 'Financial Analyst',
    education: 'Bachelor',
    city: 'Mumbai',
    country: 'India',
    purchaseFrequency: 24,
    annualSpending: 6800,
    lastPurchaseDate: '2026-07-30',
    numberOfOrders: 36,
    averageOrderValue: 188,
    preferredCategory: 'Fashion',
    customerRating: 4.9,
    clusterId: 0,
    segmentName: 'High Value / Premium Customers',
    clusterBadge: 'Premium',
    clusterColor: '#3B82F6',
    churnRisk: 'Low',
    lifetimeValue: 17030,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_3',
    customerId: 'CUST-1003',
    name: 'Emma Williams',
    age: 28,
    gender: 'Female',
    income: 52000,
    occupation: 'Graphic Designer',
    education: 'Bachelor',
    city: 'Bangalore',
    country: 'India',
    purchaseFrequency: 8,
    annualSpending: 1900,
    lastPurchaseDate: '2026-07-15',
    numberOfOrders: 10,
    averageOrderValue: 190,
    preferredCategory: 'Beauty',
    customerRating: 4.1,
    clusterId: 3,
    segmentName: 'Budget / Price Sensitive',
    clusterBadge: 'Budget',
    clusterColor: '#F59E0B',
    churnRisk: 'Medium',
    lifetimeValue: 5095,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_4',
    customerId: 'CUST-1004',
    name: 'Noah Brown',
    age: 55,
    gender: 'Male',
    income: 115000,
    occupation: 'Executive Director',
    education: 'Doctorate',
    city: 'Delhi',
    country: 'India',
    purchaseFrequency: 30,
    annualSpending: 9500,
    lastPurchaseDate: '2026-07-29',
    numberOfOrders: 45,
    averageOrderValue: 211,
    preferredCategory: 'Electronics',
    customerRating: 5.0,
    clusterId: 0,
    segmentName: 'High Value / Premium Customers',
    clusterBadge: 'Premium',
    clusterColor: '#3B82F6',
    churnRisk: 'Low',
    lifetimeValue: 23027,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_5',
    customerId: 'CUST-1005',
    name: 'Olivia Jones',
    age: 23,
    gender: 'Female',
    income: 38000,
    occupation: 'Student',
    education: 'Bachelor',
    city: 'Chennai',
    country: 'India',
    purchaseFrequency: 4,
    annualSpending: 850,
    lastPurchaseDate: '2026-06-20',
    numberOfOrders: 5,
    averageOrderValue: 170,
    preferredCategory: 'Books',
    customerRating: 3.8,
    clusterId: 4,
    segmentName: 'Inactive / At Risk',
    clusterBadge: 'Needs Marketing',
    clusterColor: '#EF4444',
    churnRisk: 'High',
    lifetimeValue: 2555,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_6',
    customerId: 'CUST-1006',
    name: 'Ethan Garcia',
    age: 31,
    gender: 'Male',
    income: 78000,
    occupation: 'Product Manager',
    education: 'Master',
    city: 'Pune',
    country: 'India',
    purchaseFrequency: 16,
    annualSpending: 3900,
    lastPurchaseDate: '2026-07-25',
    numberOfOrders: 20,
    averageOrderValue: 195,
    preferredCategory: 'Home & Kitchen',
    customerRating: 4.6,
    clusterId: 1,
    segmentName: 'Loyal Frequent Buyers',
    clusterBadge: 'Loyal',
    clusterColor: '#10B981',
    churnRisk: 'Low',
    lifetimeValue: 9907,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_7',
    customerId: 'CUST-1007',
    name: 'Ava Miller',
    age: 47,
    gender: 'Female',
    income: 64000,
    occupation: 'Teacher',
    education: 'Master',
    city: 'Kolkata',
    country: 'India',
    purchaseFrequency: 12,
    annualSpending: 2400,
    lastPurchaseDate: '2026-07-10',
    numberOfOrders: 15,
    averageOrderValue: 160,
    preferredCategory: 'Apparel',
    customerRating: 4.2,
    clusterId: 2,
    segmentName: 'Potential High-Spenders',
    clusterBadge: 'Potential',
    clusterColor: '#8B5CF6',
    churnRisk: 'Medium',
    lifetimeValue: 6520,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_8',
    customerId: 'CUST-1008',
    name: 'Mason Davis',
    age: 39,
    gender: 'Male',
    income: 102000,
    occupation: 'Data Scientist',
    education: 'Doctorate',
    city: 'Hyderabad',
    country: 'India',
    purchaseFrequency: 22,
    annualSpending: 6100,
    lastPurchaseDate: '2026-07-27',
    numberOfOrders: 28,
    averageOrderValue: 217,
    preferredCategory: 'Electronics',
    customerRating: 4.7,
    clusterId: 0,
    segmentName: 'High Value / Premium Customers',
    clusterBadge: 'Premium',
    clusterColor: '#3B82F6',
    churnRisk: 'Low',
    lifetimeValue: 14882,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_9',
    customerId: 'CUST-1009',
    name: 'Isabella Rodriguez',
    age: 29,
    gender: 'Female',
    income: 45000,
    occupation: 'Marketing Executive',
    education: 'Bachelor',
    city: 'Bangalore',
    country: 'India',
    purchaseFrequency: 7,
    annualSpending: 1600,
    lastPurchaseDate: '2026-06-30',
    numberOfOrders: 8,
    averageOrderValue: 200,
    preferredCategory: 'Beauty',
    customerRating: 3.9,
    clusterId: 4,
    segmentName: 'Inactive / At Risk',
    clusterBadge: 'Needs Marketing',
    clusterColor: '#EF4444',
    churnRisk: 'High',
    lifetimeValue: 4340,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'cust_10',
    customerId: 'CUST-1010',
    name: 'James Wilson',
    age: 51,
    gender: 'Male',
    income: 88000,
    occupation: 'Consultant',
    education: 'Master',
    city: 'Mumbai',
    country: 'India',
    purchaseFrequency: 19,
    annualSpending: 4800,
    lastPurchaseDate: '2026-07-24',
    numberOfOrders: 25,
    averageOrderValue: 192,
    preferredCategory: 'Sports',
    customerRating: 4.5,
    clusterId: 1,
    segmentName: 'Loyal Frequent Buyers',
    clusterBadge: 'Loyal',
    clusterColor: '#10B981',
    churnRisk: 'Low',
    lifetimeValue: 12120,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export let mockCustomersStore: MockCustomer[] = [...initialMockCustomers];

export const setMockCustomersStore = (newStore: MockCustomer[]) => {
  mockCustomersStore = newStore;
};
